services:
  terrad:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TERRA_VERSION: ${TERRA_VERSION}
    image: ghcr.io/terra-money/localterra:${TERRA_VERSION}
    hostname: terrad
    pull_policy: always
    volumes:
      - terra:/app
    networks:
      - default
    ports:
      - "1317:1317"
      - "8080:8080"
      - "9090:9090"
      - "9091:9091"
      - "26657:26657"

volumes:
  terra:

networks:
  default:
